Repository Ratnesh-Team/Rehabify, pull requests merged in 2024-10, with the labels that each got.

#48 Implement Role-Based Access Control for Backend API #39
  Backend/controllers/NMK_controllers.go
Labels: gssoc-ext, level 1

#68 Update User API migration and Postgresql DB
  Backend/config/postgre_config.go
  Backend/controllers/user_controllers.go
  Backend/go.mod
  Backend/go.sum
  Backend/main.go
  Backend/postgresql/migration/user_schema.sql
  Backend/postgresql/query/user_query.sql
  Backend/projects/db.go
  Backend/projects/models.go
  Backend/projects/user_query.sql.go
  Backend/repository/postgre_repository.go
  Backend/routes/routes.go
  Backend/sqlc.yaml
Labels: hacktoberfest-accepted, gssoc-ext, level 3, level 2

#71 Added Error Message for Network Error
  Backend/Procfile
  Frontend/sample.env
  Frontend/src/utils/hooks/useAuth.ts
  Frontend/src/views/Database/Database.tsx
  Frontend/src/views/Doctor/popup.tsx
  Frontend/src/views/HomeRemedies/HomeRemedies.tsx
  Frontend/src/views/HomeRemedies/cardData.ts
  Frontend/src/views/TreatmentCenters/TreatmentCenters.tsx
  Frontend/src/views/auth/ForgotPassword/ForgotPasswordForm.tsx
  Frontend/src/views/auth/ResetPassword/ResetPasswordForm.tsx
Labels: hacktoberfest-accepted, gssoc-ext, level 1

#79 stats section countup added #72 done
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/views/Home/Home.tsx
Labels: hacktoberfest-accepted, gssoc-ext, level 1

#85 Multilingual Support for Rehabify
  Frontend/src/components/template/Footer.tsx
  Frontend/src/services/GoogleTranslate.tsx
Labels: hacktoberfest-accepted, gssoc-ext, level 2

#92 Added the contributors page and in navbar also i added link for contributors page.
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/components/layouts/ClassicLayout.tsx
  Frontend/src/components/layouts/DeckedLayout.tsx
  Frontend/src/components/layouts/ModernLayout.tsx
  Frontend/src/components/layouts/SimpleLayout.tsx
  Frontend/src/components/layouts/StackedSideLayout.tsx
  Frontend/src/components/template/ContributorPage/Contributor.tsx
  Frontend/src/components/template/ContributorPage/index.ts
  Frontend/src/configs/navigation-icon.config.tsx
  Frontend/src/configs/navigation.config/index.ts
  Frontend/src/configs/routes.config/routes.config.ts
  Frontend/src/views/Contributor/Contributor.tsx
  Frontend/src/views/Contributor/index.tsx
Labels: hacktoberfest-accepted, gssoc-ext, level 3

#93 Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted, gssoc-ext, level 1

#101 UI enhancement in Doctor Appointment Section
  Frontend/package-lock.json
  Frontend/src/views/Doctor/popup.tsx
Labels: hacktoberfest-accepted, gssoc-ext, level 1

#118 fixed typo
  README.md
Labels: gssoc-ext

#115 Fixed card-layout and centred pagination
  Frontend/src/views/Doctor/popup.tsx
  Frontend/src/views/TreatmentCenters/TreatmentCenters.tsx
Labels: hacktoberfest-accepted, gssoc-ext, level 1

#119 fix: fixed the responsivness over required sections issue#50
  Frontend/src/components/template/Footer.tsx
  Frontend/src/views/Database/Database.tsx
  Frontend/src/views/Home/Home.tsx
  Frontend/src/views/TreatmentCenters/TreatmentCenters.tsx
Labels: hacktoberfest-accepted, gssoc-ext, level 1

#113 Added Appointment Form Added with Form Validation to the doctor page
  Frontend/src/components/ui/Button/Button.tsx
  Frontend/src/views/Doctor/popup.tsx
Labels: hacktoberfest-accepted, gssoc-ext, level 2

#130 fixed the cards layout and made it consistent on all pages #62
  Frontend/src/views/Doctor/popup.tsx
Labels: hacktoberfest-accepted, gssoc-ext, level 1

#136 The implementation of a Testimonial card feature. (Issue #129)
  Frontend/package-lock.json
  Frontend/sample.env
  Frontend/src/views/Home/Home.tsx
  Frontend/src/views/testimonal/Testimonials.tsx
  Frontend/src/views/testimonal/image (1).png
  Frontend/src/views/testimonal/image.png
  Frontend/src/views/testimonal/testimonal.jpg
Labels: hacktoberfest-accepted, gssoc-ext, level 1

#137 Dockerize backend #133
  Backend/.dockerIgnore
  Backend/Dockerfile
  README.md
Labels: hacktoberfest-accepted, gssoc-ext, level 2

#144 fix: Enhanced User Registration Form Validation #112
  Frontend/src/views/Register/userRegisteration.tsx
Labels: hacktoberfest-accepted, gssoc-ext, level 1
